#!/usr/bin/env python3
"""Replace the tables embedded in manuscript.md with the current generated ones.

Tables are embedded in the manuscript because BMJ requires them in place at first
citation, but they are generated by analysis.py. Without this step the manuscript
keeps a stale snapshot whenever the analysis is re-run.
"""
import re
import sys
from pathlib import Path

MAP = {"Table 1": "table1_documents.md",
       "Table 2": "table2_scenarios.md",
       "Table 3": "table3_sensitivity.md"}

md = Path("manuscript.md")
text = md.read_text()
changed = []

for label, fname in MAP.items():
    fresh = Path("tables", fname).read_text().strip()
    # the caption line, then anything up to the next blank line that is not table
    # or footnote content
    pat = re.compile(rf"(\*\*{label}\*\*[^\n]*\n\n)(.*?)(?=\n\n(?:#|\*\*Table|[A-Z][a-z]))",
                     re.S)
    m = pat.search(text)
    if not m:
        sys.exit(f"could not locate the embedded block for {label}")
    if m.group(2).strip() != fresh:
        text = text[:m.start(2)] + fresh + text[m.end(2):]
        changed.append(label)

md.write_text(text)
print("synced:", ", ".join(changed) if changed else "already current")
