#!/usr/bin/env python3
"""Replace the tables embedded in the manuscript and supplementary with the generated ones.

BMJ wants tables in the main text at first citation, but they are generated by
analysis.py, so the embedded copies must be refreshed rather than hand-edited.

The block belonging to a caption runs from the caption to the next heading or
the next table caption; that includes the table's own footnote paragraph, which
is part of the generated file. Anything narrower duplicates the footnote on
every run.
"""
import re
import sys
from pathlib import Path

DOCS = [("manuscript.md", {"Table 1": "table1_documents.md",
                           "Table 2": "table2_scenarios.md",
                           "Table 3": "table3_sensitivity.md"}),
        ("supplementary.md", {"SUPPLEMENTARY TABLE S1": "tableS1_parameters.md",
                              "SUPPLEMENTARY TABLE S2": "tableS2_cost_detail.md"})]

changed = []
for doc, mapping in DOCS:
    md = Path(doc)
    text = md.read_text()
    for label, fname in mapping.items():
        fresh = Path("tables", fname).read_text().strip()
        if label.startswith("SUPPLEMENTARY"):
            # the supplementary carries the table under a heading and a lead line
            pat = re.compile(rf"(# {label}\n\n[^\n|]*\n\n)(\|.*?)(?=\n\n---|\Z)", re.S)
        else:
            pat = re.compile(
                rf"(\*\*{label}\*\*[^\n]*\n\n)(.*?)(?=\n\n(?:#{{1,3}} |\*\*Table \d))",
                re.S)
        m = pat.search(text)
        if not m:
            sys.exit(f"could not locate the embedded block for {label} in {doc}")
        if m.group(2).strip() != fresh:
            text = text[:m.start(2)] + fresh + text[m.end(2):]
            changed.append(f"{doc}:{label}")
    md.write_text(text)

print("synced:", ", ".join(changed) if changed else "already current")
